### ISSUE TITLE
Fuse dependency not fully installed on Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by lczech** [delehef/fusta#1]
Hi there,

your readme states that

> On most GNU/Linux distributions, FUSE is installed by default. Otherwise, you should install it from your package manager – note that a reboot might be necessary for the kernel module to be loaded.

However, on Ubuntu 20.04.4 LTS, I first needed 

    sudo apt-get install fuse3 # might not have been necessary
    sudo apt-get install libfuse3-* # installs libfuse3-3 and libfuse3-dev

I thought you might want to add to the readme that one of the `libfuse` dependencies might need to be install first. I am not sure which one of the two (`libfuse3-3` and `libfuse3-dev`) was the one that actually was needed, but after that, I was able to `cargo install` fusta.

Cheers, and thanks
Lucas

**Comment by delehef** [comment]
Hi Lucas,

Thanks for your feedback.

I added more distribution/OS-specific details to the README, hopefully that will help newcomers.

Cheers,

Franklin

**Comment by lczech** [comment]
Wow, that was quick, and is quite thorough now! Thanks!
