### ISSUE TITLE
Suggestion: default `--mountpoint` is file name without extension

### ISSUE THREAD

**Issue by lczech** [delehef/fusta#2]
Hi there,

as an idea: Would it make sense to use the file name without extension as the default name for the mount point, instead of `fusta`? That would make it easier to work with multiple fusta-mounted files at the same time.

Cheers
Lucas

**Comment by delehef** [comment]
I like the idea. I would probably still keep a `fusta` prefix or suffix, so that no ill-fated auto-completed `rm` deletes the original files.

**Comment by lczech** [comment]
Awesome, thanks ;-)
