### ISSUE TITLE
Copying files to append/ fails with I/O error

### ISSUE THREAD

**Issue by Cydhra** [delehef/fusta#7]
Attempting to copy/move/create files in the append directory always fails with an Input/Output error:
```
cp: error writing 'manual/append/test2.fa': Input/output error
```
I can map test2.fa, but I cannot append it to other files. I can't provide much more detail, as this is the only information I am getting. 
I tried cp, mv, creating a file manually, and piping cat output.
I tried installing the latest commit using `cargo install --git ...` and I tried the latest release using `cargo install --git ... --tag v1.7.1`

OS is Fedora 40.
Fuse is version 3.16.2-3 from the fedora repos

**Comment by delehef** [comment]
Would you mind sharing the FASTA file so that I can reproduce in the same conditions?

**Comment by Cydhra** [comment]
Had to rename them .txt so github would let me upload them.

```bash
fusta -o manual test.txt
cat manual/seqs/test.seq # works

cp test2.txt manual/append # error
```

[test.txt](https://github.com/user-attachments/files/17278411/test.txt)
[test2.txt](https://github.com/user-attachments/files/17278414/test2.txt)

**Comment by delehef** [comment]
Thank you for your patience.

Could you please confirm that that latest `master` fixes the issue?

**Comment by Cydhra** [comment]
Confirmed fixed!
